# Generated by Django 5.2.7 on 2025-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_assignment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved')], default='Available', max_length=10),
        ),
    ]
